Agrega efectos de sonido
MarioGabIFP/Super_Paco_Bros pull request #13
Opened 2022-04-20 18:39 UTC by PaoloSaldana

2022-04-21 18:15 UTC, MarioGabIFP submitted a review, later dismissed
Hola Paolo, implementa estos mismos cambios en la nueva implementación, de momento voy a cerrar esta petición, ya que deberás rehacer tu rama y modificar sobre mis cambios una vez sea aprobada mi petición de pull request, cuando la aprobéis avísame y te ayudo a hacer esto que te digo

2022-04-28 08:20 UTC, MarioGabIFP commented
Hola Paolo, Implemento los sonidos añadidos en la nueva estructura del juego como te dije :)

2022-04-28 08:24 UTC, MarioGabIFP requested changes
Hola Paolo, he descubierto como podemos mergear tu rama sin  que afecte al estado actual del master, hoy te digo como

2022-05-03 07:49 UTC, PaoloSaldana commented
Hecho en #20

2022-05-03 07:49 UTC, closed without merging